// AR translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const ar: Record<string, string> = {
  "approval.actions.approve": "موافقة",
  "approval.actions.direct_publish": "نشر مباشر",
  "approval.actions.reject": "رفض",
  "approval.actions.request_changes": "طلب تعديلات",
  "approval.actions.resubmit": "إعادة إرسال",
  "approval.actions.submit": "إرسال للمراجعة",
  "approval.messages.already_submitted": "هذا المنتج تم إرساله للمراجعة مسبقاً",
  "approval.messages.approved": "تمت الموافقة على المنتج بنجاح",
  "approval.messages.approved_direct": "تمت الموافقة على المنتج — يمكنك النشر الآن",
  "approval.messages.changes_requested": "تم طلب تعديلات",
  "approval.messages.direct_publish_confirm": "هل تريد نشر هذا المنتج مباشرة دون مراجعة؟",
  "approval.messages.fix_and_resubmit": "أصلح المشكلات وأعد الإرسال للمراجعة",
  "approval.messages.not_submitted": "لم يتم إرسال هذا المنتج بعد",
  "approval.messages.ready_to_deploy": "جاهز للنشر",
  "approval.messages.reject_reason_required": "يرجى كتابة سبب الرفض",
  "approval.messages.rejected": "تم رفض المنتج",
  "approval.messages.submit_confirm": "هل أنت متأكد من إرسال هذا المنتج للمراجعة؟",
  "approval.messages.submitted": "تم إرسال المنتج للمراجعة",
  "approval.messages.under_review": "هذا المنتج قيد المراجعة حالياً. لا يزال بإمكانك تعديله.",
  "approval.status.approved": "تمت الموافقة",
  "approval.status.changes_requested": "مطلوب تعديلات",
  "approval.status.draft": "مسودة",
  "approval.status.pending_review": "بانتظار المراجعة",
  "approval.status.rejected": "مرفوض",
};
