// AR translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const ar: Record<string, string> = {
  "notifications.ago": "منذ",
  "notifications.all_read": "لا توجد إشعارات جديدة!",
  "notifications.empty": "لا توجد إشعارات بعد",
  "notifications.just_now": "الآن",
  "notifications.mark_all_read": "تعليم الكل كمقروء",
  "notifications.title": "الإشعارات",
  "notifications.unread": "غير مقروء",
};
