// AR translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const ar: Record<string, string> = {
  "sales.capacityReached": "تم الوصول للسعة القصوى",
  "sales.dealEvaluation": "تقييم الصفقات",
  "sales.finalizeDeal": "إنهاء الصفقة",
  "sales.pendingSync": "بانتظار المزامنة",
  "sales.reviewQueueSubtitle": "صفقات نشطة تحتاج اهتمام",
  "sales.thresholdUnlocked": "تم تجاوز الحد الأدنى",
};
