// AR translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const ar: Record<string, string> = {
  "service.dashboard.description": "نظرة عامة ومؤشرات الأداء",
  "service.dashboard.name": "لوحة التحكم",
  "service.marketplace.description": "المنتجات، المزادات، وقنوات البيع",
  "service.marketplace.name": "إدارة العروض",
  "service.reports.description": "التحليلات والتصدير",
  "service.reports.name": "التقارير",
  "service.sales.description": "الطلبات والعملاء",
  "service.sales.name": "المبيعات",
  "service.sidebar.auctions.name": "المزادات",
  "service.sidebar.catalog.name": "الكتالوج",
  "service.sidebar.commerce.name": "التجارة",
  "service.sidebar.customers.name": "العملاء",
  "service.sidebar.dashboard.name": "لوحة التحكم",
  "service.sidebar.dashboards.name": "لوحات التحكم",
  "service.sidebar.general.name": "عام",
  "service.sidebar.inventory.name": "المخزون",
  "service.sidebar.management.name": "الإدارة",
  "service.sidebar.marketplace.name": "السوق",
  "service.sidebar.operations.name": "العمليات",
  "service.sidebar.orders.name": "الطلبات",
  "service.sidebar.reports.name": "التقارير",
  "service.sidebar.sales.name": "المبيعات",
  "service.sidebar.settings.name": "الإعدادات",
  "service.sidebar.settings_section.name": "الإعدادات",
};
