// AR translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const ar: Record<string, string> = {
  "support.email": "البريد الإلكتروني",
  "support.email_desc": "نرد خلال 24 ساعة",
  "support.email_label": "بريدك الإلكتروني",
  "support.email_placeholder": "your@email.com",
  "support.form_title": "أرسل لنا رسالة",
  "support.message_label": "الرسالة",
  "support.message_placeholder": "صف مشكلتك أو سؤالك...",
  "support.phone": "الهاتف",
  "support.phone_desc": "الأحد–الخميس، 9 ص–5 م",
  "support.send": "إرسال الرسالة",
  "support.sending": "جاري الإرسال...",
  "support.sent": "تم إرسال الرسالة بنجاح!",
  "support.sent_desc": "سنعود إليك في أقرب وقت ممكن.",
  "support.subject_label": "الموضوع",
  "support.subject_placeholder": "كيف يمكننا مساعدتك؟",
  "support.subtitle": "احصل على مساعدة من فريق الدعم",
  "support.title": "الدعم",
  "support.whatsapp": "واتساب",
  "support.whatsapp_desc": "ردود سريعة متاحة",
};
