/**
 * One-shot generator: splits the monolithic en/ar translation objects into
 * per-feature files under src/translations/features/<locale>/ and rewrites
 * src/translations/<locale>.ts as a barrel merge.
 *
 * Run with:  npx tsx scripts/split-translations.ts
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { en } = require('../src/translations/en');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { ar } = require('../src/translations/ar');

type Bundle = Record<string, string>;
type Locale = 'en' | 'ar';

const SRC_TRANSLATIONS = path.resolve(__dirname, '..', 'src', 'translations');

/**
 * Map a dotted key to a feature bucket. Returns the folder name used under
 * translations/features/<locale>/.
 */
function keyToFeature(key: string): string {
  const head = key.split('.', 1)[0];
  switch (head) {
    case 'listing':
    case 'amazon':
      return 'listings';
    case 'auction':
    case 'critical':
    case 'bid_ticker':
    case 'live':
      return 'auctions';
    case 'group_buying':
    case 'groupBuying':
    case 'group':
    case 'deal':
      return 'group-buying';
    case 'category':
      return 'categories';
    case 'merchant':
      return 'merchants';
    case 'moderation':
      return 'moderation';
    case 'feedback':
      return 'feedback';
    case 'report':
      return 'reports';
    case 'orders':
      return 'orders';
    case 'inventory':
      return 'inventory';
    case 'customer':
      return 'customers';
    case 'settlement':
      return 'settlements';
    case 'sales':
      return 'sales';
    case 'approval':
      return 'approvals';
    case 'support':
      return 'support';
    case 'service':
      return 'service-desk';
    case 'toast':
      return 'toasts';
    case 'sidebar':
    case 'topbar':
    case 'dashboard':
    case 'dash':
      return 'navigation';
    case 'settings':
    case 'profile':
    case 'user':
    case 'roles':
      return 'account';
    case 'auth':
    case 'auth_guard':
      return 'auth';
    case 'notifications':
      return 'notifications';
    case 'mobile':
    case 'help':
      return 'help';
    case 'boot':
    case 'common':
    case 'validation':
    case 'datatable':
    case 'status':
    case 'offline':
    case 'upload':
    case 'stats':
    case 'portal':
    case 'prod':
    case 'iqd':
      return 'common';
    default:
      return 'common';
  }
}

function escapeKey(key: string): string {
  // Quote keys that contain characters needing escaping or reserved words.
  if (/^[A-Za-z_$][\w$]*$/.test(key)) return key;
  return JSON.stringify(key);
}

function escapeValue(value: string): string {
  // Use JSON.stringify for safe escaping of all special characters.
  return JSON.stringify(value);
}

function writeFeatureFile(filePath: string, entries: Array<[string, string]>, locale: Locale): void {
  const lines: string[] = [];
  lines.push(`// ${locale.toUpperCase()} translations: feature module (auto-generated by scripts/split-translations.ts)`);
  lines.push('// Do not edit the generator; edit keys here directly or add new ones following the same shape.');
  lines.push('');
  lines.push(`export const ${locale}: Record<string, string> = {`);
  // Sort keys alphabetically within a feature file for stable diffs.
  const sorted = entries.slice().sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  for (const [key, value] of sorted) {
    lines.push(`  ${escapeKey(key)}: ${escapeValue(value)},`);
  }
  lines.push('};');
  lines.push('');
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
}

function splitBundle(bundle: Bundle, locale: Locale): Map<string, Array<[string, string]>> {
  const features = new Map<string, Array<[string, string]>>();
  for (const [key, value] of Object.entries(bundle)) {
    const feature = keyToFeature(key);
    let bucket = features.get(feature);
    if (!bucket) {
      bucket = [];
      features.set(feature, bucket);
    }
    bucket.push([key, value]);
  }
  return features;
}

function processLocale(locale: Locale, bundle: Bundle): string[] {
  const featuresDir = path.join(SRC_TRANSLATIONS, 'features', locale);
  fs.mkdirSync(featuresDir, { recursive: true });

  const features = splitBundle(bundle, locale);
  const featureFiles: string[] = [];
  for (const [feature, entries] of features) {
    const fileBase = `${feature}.ts`;
    const filePath = path.join(featuresDir, fileBase);
    writeFeatureFile(filePath, entries, locale);
    featureFiles.push(feature);
  }

  // features/<locale>/index.ts — barrel of all feature modules.
  const indexLines: string[] = [];
  indexLines.push(`// ${locale.toUpperCase()} feature translations barrel (auto-generated).`);
  indexLines.push('');
  for (const feature of featureFiles) {
    indexLines.push(`export { ${locale} as ${feature.replace(/-/g, '_')} } from './${feature}';`);
  }
  indexLines.push('');
  fs.writeFileSync(path.join(featuresDir, 'index.ts'), indexLines.join('\n'), 'utf8');

  return featureFiles;
}

function writeRootBarrel(locale: Locale, featureFiles: string[]): void {
  const rootFile = path.join(SRC_TRANSLATIONS, `${locale}.ts`);
  const lines: string[] = [];
  lines.push(`// ${locale.toUpperCase()} root translations — barrel merge of all feature modules.`);
  lines.push('// Source of truth now lives under src/translations/features/' + locale + '/.');
  lines.push('// To add a key, append it to the relevant feature file in that folder.');
  lines.push('');
  const importNames = featureFiles.map((f) => f.replace(/-/g, '_'));
  lines.push(`import { ${importNames.join(', ')} } from './features/${locale}';`);
  lines.push('');
  lines.push(`export const ${locale}: Record<string, string> = {`);
  for (const name of importNames) {
    lines.push(`  ...${name},`);
  }
  lines.push('};');
  lines.push('');
  fs.writeFileSync(rootFile, lines.join('\n'), 'utf8');
}

function main(): void {
  const enFeatures = processLocale('en', en as Bundle);
  const arFeatures = processLocale('ar', ar as Bundle);

  // Sanity: both locales should produce the same feature buckets.
  const enSet = new Set(enFeatures);
  const arSet = new Set(arFeatures);
  const onlyEn = enFeatures.filter((f) => !arSet.has(f));
  const onlyAr = arFeatures.filter((f) => !enSet.has(f));
  if (onlyEn.length || onlyAr.length) {
    console.warn(
      '[split-translations] feature buckets differ between locales:',
      { onlyEn, onlyAr },
    );
  }

  const allFeatures = Array.from(new Set([...enFeatures, ...arFeatures])).sort();
  writeRootBarrel('en', allFeatures);
  writeRootBarrel('ar', allFeatures);

  console.log('[split-translations] done. features:', allFeatures.join(', '));
}

main();
