// EN translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const en: Record<string, string> = {
  "approval.actions.approve": "Approve",
  "approval.actions.direct_publish": "Publish Directly",
  "approval.actions.reject": "Reject",
  "approval.actions.request_changes": "Request Changes",
  "approval.actions.resubmit": "Resubmit",
  "approval.actions.submit": "Submit for Review",
  "approval.messages.already_submitted": "This product is already submitted for review",
  "approval.messages.approved": "Product approved successfully",
  "approval.messages.approved_direct": "Product approved — you can publish now",
  "approval.messages.changes_requested": "Changes requested",
  "approval.messages.direct_publish_confirm": "Publish this product directly without moderation review?",
  "approval.messages.fix_and_resubmit": "Fix the issues and resubmit for review",
  "approval.messages.not_submitted": "This product has not been submitted yet",
  "approval.messages.ready_to_deploy": "Ready to Deploy",
  "approval.messages.reject_reason_required": "Please provide a rejection reason",
  "approval.messages.rejected": "Product rejected",
  "approval.messages.submit_confirm": "Are you sure you want to submit this product for review?",
  "approval.messages.submitted": "Product submitted for review",
  "approval.messages.under_review": "This product is currently under review. You can still edit it.",
  "approval.status.approved": "Approved",
  "approval.status.changes_requested": "Changes Requested",
  "approval.status.draft": "Draft",
  "approval.status.pending_review": "Pending Review",
  "approval.status.rejected": "Rejected",
};
