// EN translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const en: Record<string, string> = {
  "notifications.ago": "ago",
  "notifications.all_read": "All caught up!",
  "notifications.empty": "No notifications yet",
  "notifications.just_now": "Just now",
  "notifications.mark_all_read": "Mark all as read",
  "notifications.title": "Notifications",
  "notifications.unread": "unread",
};
