// EN translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const en: Record<string, string> = {
  "sales.capacityReached": "Capacity Reached",
  "sales.dealEvaluation": "Deal Evaluation",
  "sales.finalizeDeal": "Finalize Deal",
  "sales.pendingSync": "Pending Sync",
  "sales.reviewQueueSubtitle": "Active deals requiring attention",
  "sales.thresholdUnlocked": "Threshold Unlocked",
};
