// EN translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const en: Record<string, string> = {
  "service.dashboard.description": "Overview and KPIs",
  "service.dashboard.name": "Dashboard",
  "service.marketplace.description": "Products, auctions, and sales channels",
  "service.marketplace.name": "Offer Management",
  "service.reports.description": "Analytics and exports",
  "service.reports.name": "Reports",
  "service.sales.description": "Orders and customers",
  "service.sales.name": "Sales",
  "service.sidebar.auctions.name": "Auctions",
  "service.sidebar.catalog.name": "Catalog",
  "service.sidebar.commerce.name": "Commerce",
  "service.sidebar.customers.name": "Customers",
  "service.sidebar.dashboard.name": "Dashboard",
  "service.sidebar.dashboards.name": "Dashboards",
  "service.sidebar.general.name": "General",
  "service.sidebar.inventory.name": "Inventory",
  "service.sidebar.management.name": "Management",
  "service.sidebar.marketplace.name": "Marketplace",
  "service.sidebar.operations.name": "Operations",
  "service.sidebar.orders.name": "Orders",
  "service.sidebar.reports.name": "Reports",
  "service.sidebar.sales.name": "Sales",
  "service.sidebar.settings.name": "Settings",
  "service.sidebar.settings_section.name": "Settings",
};
