// EN translations: feature module (auto-generated by scripts/split-translations.ts)
// Do not edit the generator; edit keys here directly or add new ones following the same shape.

export const en: Record<string, string> = {
  "support.email": "Email",
  "support.email_desc": "We respond within 24 hours",
  "support.email_label": "Your Email",
  "support.email_placeholder": "your@email.com",
  "support.form_title": "Send us a message",
  "support.message_label": "Message",
  "support.message_placeholder": "Describe your issue or question...",
  "support.phone": "Phone",
  "support.phone_desc": "Sun-Thu, 9AM - 5PM",
  "support.send": "Send Message",
  "support.sending": "Sending...",
  "support.sent": "Message sent successfully!",
  "support.sent_desc": "We'll get back to you as soon as possible.",
  "support.subject_label": "Subject",
  "support.subject_placeholder": "How can we help?",
  "support.subtitle": "Get help from our support team",
  "support.title": "Support",
  "support.whatsapp": "WhatsApp",
  "support.whatsapp_desc": "Quick responses available",
};
